create or replace PROCEDURE WEB_CATNETSUITE (  
  CVETDA_ IN INTEGER DEFAULT 0,
  CVERES_ IN INTEGER,  
  OUT_RESULTSET OUT SYS_REFCURSOR
) IS

BEGIN
  IF CVETDA_ <> 0 THEN
    OPEN OUT_RESULTSET FOR
      SELECT IDNETSUITE FROM VENTAS.INTEGRA_TIENDAS WHERE IDCHAPUR = CVETDA_;
  ELSE
    OPEN OUT_RESULTSET FOR
      SELECT IDNETSUITE FROM VENTAS.INTEGRA_RESTAURANTES WHERE IDCHAPUR = CVERES_;
  END IF;
END WEB_CATNETSUITE;