create or replace PROCEDURE WEB_VALIDAOPRCAJ_REST(
  P_TIENDA INTEGER,
  P_FOLIOSVA INTEGER,
  P_FECHA DATE,
  P_IMPORTE DOUBLE PRECISION,
  OUT_RESULTSET OUT SYS_REFCURSOR,
  P_OPRCAJ OUT INTEGER
) IS

  rRET CR_RESULTEXITO := CR_RESULTEXITO(0, NULL);
  tRET CT_RESULTEXITO := CT_RESULTEXITO();
    
  CURSOR C_REGSVA(V_TIENDA INTEGER,V_FOLIOSVA INTEGER,V_FECHA DATE) IS
    SELECT OPRCAJ,(IMPORTE-NVL((SELECT SUM((CANTIDAD*PPUBLICO)-DESCTO+IVA) 
                                FROM VENTAS.PVRENPAG 
                                WHERE PVRENPAG.CVETDA = CONCILIACIONSVA.CVETDA 
                                  AND PVRENPAG.OPRCAJ = CONCILIACIONSVA.OPRCAJ 
                                  AND PVRENPAG.NUMART = 2027480),0)) AS IMPORTE,STATUS 
    FROM VENTAS.CONCILIACIONSVA 
    WHERE FOLIOSVA = V_FOLIOSVA 
      AND CVETDA = V_TIENDA 
      AND TRUNC(FECHA) = V_FECHA;
      
  CURSOR C_CONSULTA (P_OPERACION INTEGER,P_TIENDA INTEGER) IS
    SELECT VENTAS.PVIDEOPR.IDFAC, VENTAS.PVIDEOPR.FECHA, VENTAS.PVIDEOPR.STATUS, VENTAS.PVIDEOPR.TIPO_FACTURACION, VENTAS.PVIDEOPR.TIPOPR, ROUND(TOTOPR,2) AS TOTAL_OPR 
    FROM VENTAS.PVIDEOPR 
    WHERE VENTAS.PVIDEOPR.CVETDA = P_TIENDA and OPRCAJ = P_OPERACION;  
    
  R_CONSULTA C_CONSULTA%ROWTYPE;

  CURSOR C_VALIDA_BILLETERA(P_OPERACION INTEGER,P_TIENDA INTEGER) IS
    select COUNT(*) 
    from ventas.pvpagope 
    where oprcaj = P_OPERACION 
      and cvetda = P_TIENDA 
      and TIPPAG = 8 
      and SBTPAG = 1 
      AND TPAGAR > 0;
    
  DIFERENCIA DOUBLE PRECISION;
  NOVALIDO INTEGER;
  FECHA_ACTUAL DATE;
    
  V_OPRCAJ INTEGER;
  V_IMPORTE DOUBLE PRECISION;
  V_STATUS INTEGER;

BEGIN
  IF P_TIENDA IS NULL THEN
    rRET.EXITO := 0;
    rRET.MENSAJE := 'LA TIENDA ES REQUERIDA';
    tRET.EXTEND;
    tRET(tRET.LAST) := rRET;
    GOTO SALIDA;
  END IF;
  
  IF P_FOLIOSVA IS NULL THEN
    rRET.EXITO := 0;
    rRET.MENSAJE := 'EL FOLIO ES REQUERIDO';
    tRET.EXTEND;
    tRET(tRET.LAST) := rRET;
    GOTO SALIDA;
  END IF;
  
  IF P_FECHA IS NULL THEN
    rRET.EXITO := 0;
    rRET.MENSAJE := 'LA FECHA ES REQUERIDA';
    tRET.EXTEND;
    tRET(tRET.LAST) := rRET;
    GOTO SALIDA;
  END IF;
  
  IF P_IMPORTE IS NULL THEN
    rRET.EXITO := 0;
    rRET.MENSAJE := 'EL IMPORTE ES REQUERIDO';
    tRET.EXTEND;
    tRET(tRET.LAST) := rRET;
    GOTO SALIDA;
  END IF;

  FECHA_ACTUAL := NULL;
  DIFERENCIA := 0.0;
  SELECT TRUNC(SYSDATE) INTO FECHA_ACTUAL FROM DUAL;
  
  OPEN C_REGSVA(P_TIENDA,P_FOLIOSVA,P_FECHA);
  FETCH C_REGSVA INTO V_OPRCAJ,V_IMPORTE,V_STATUS;
  CLOSE C_REGSVA;
  
  IF V_OPRCAJ IS NULL THEN
    rRET.EXITO := 0;
    rRET.MENSAJE := 'NO SE ENCONTRO NINGUNA OPERACION';
    tRET.EXTEND;
    tRET(tRET.LAST) := rRET;
    GOTO SALIDA;
  END IF;
  
  IF V_STATUS = 1 THEN
    rRET.EXITO := 0;
    rRET.MENSAJE := 'LA OPERACIÓN SE ENCUENTRA CANCELADA';
    tRET.EXTEND;
    tRET(tRET.LAST) := rRET;
    GOTO SALIDA;
  END IF;
  
  DIFERENCIA := V_IMPORTE-P_IMPORTE;
  IF DIFERENCIA > 1 OR DIFERENCIA < -1 THEN
    rRET.EXITO := 0;
    rRET.MENSAJE := 'EL IMPORTE DE LA OPERACIÓN ES INCORRECTO';
    tRET.EXTEND;
    tRET(tRET.LAST) := rRET;
    GOTO SALIDA;
  END IF;
  
  OPEN C_CONSULTA(V_OPRCAJ,P_TIENDA);
    FETCH C_CONSULTA INTO R_CONSULTA;
    
    IF C_CONSULTA%NOTFOUND THEN
      rRET.EXITO := 0;
      rRET.MENSAJE := 'LA OPERACION DE CAJA EN LA TIENDA NO EXISTE';
    ELSE
      IF R_CONSULTA.IDFAC > 0 AND R_CONSULTA.TIPO_FACTURACION = 1 THEN
        rRET.EXITO := -1;
        rRET.MENSAJE := 'LA OPERACION DE CAJA YA SE ENCUENTRA FACTURADA';
      ELSIF R_CONSULTA.STATUS = 1 THEN 
        rRET.EXITO := 0;
        rRET.MENSAJE := 'LA OPERACION DE CAJA SE ENCUENTRA CANCELADA';
      ELSIF R_CONSULTA.TIPOPR <> 1 THEN
        rRET.EXITO := 2;
        rRET.MENSAJE := 'LA OPERACION NO ES UNA OPERACION DE COMPRA';
      ELSIF R_CONSULTA.TIPO_FACTURACION = 2 THEN
        rRET.EXITO := 0;
        rRET.MENSAJE := 'LA OPERACION SE ENCUENTRA FACTURADA GLOBALMENTE';
      ELSIF TO_CHAR(FECHA_ACTUAL,'YYYY') <> TO_CHAR(R_CONSULTA.FECHA,'YYYY') THEN
        rRET.EXITO := 0;
        rRET.MENSAJE := 'LA OPERACION NO ES DEL AÑO ACTUAL';
      ELSIF TO_CHAR(FECHA_ACTUAL,'MM') <> TO_CHAR(R_CONSULTA.FECHA,'MM') THEN
        rRET.EXITO := 0;
        rRET.MENSAJE := 'LA OPERACION NO ES DEL MES ACTUAL';
      ELSE
        P_OPRCAJ := V_OPRCAJ;
        OPEN C_VALIDA_BILLETERA(V_OPRCAJ,P_TIENDA);
        FETCH C_VALIDA_BILLETERA INTO NOVALIDO;
        CLOSE C_VALIDA_BILLETERA;
        
        IF NOVALIDO > 0 THEN
          rRET.EXITO := 3;
          rRET.MENSAJE := 'LA OPERACION PUEDE SER FACTURADA, PERO SOLAMENTE CON RFC GENERICO';
        ELSE
          rRET.EXITO := 1;
          rRET.MENSAJE := 'LA OPERACION PUEDE SER FACTURADA';
        END IF;
      END IF;
    END IF;
  CLOSE C_CONSULTA;
    
  tRET.EXTEND;
  tRET(tRET.LAST) := rRET;
  <<SALIDA>>
    
  OPEN OUT_RESULTSET FOR
    SELECT 
      T.EXITO,
      T.MENSAJE
    FROM TABLE (CAST(tRET AS VENTAS.CT_RESULTEXITO)) T;
END;
