create or replace PROCEDURE WEB_VALIDAOPRCAJFACMOTO (
  OPRCAJ_ IN INTEGER, 
  TIENDA_ IN INTEGER,  
  IMPORTE IN DOUBLE PRECISION,
  OUT_RESULTSET OUT SYS_REFCURSOR
) IS

  tRET VENTAS.CT_RESULTEXITO := VENTAS.CT_RESULTEXITO();
  rRET VENTAS.CR_RESULTEXITO := VENTAS.CR_RESULTEXITO(0, NULL);

  FECHA_ACTUAL DATE;
  CURSOR C_VALIDACION (P_OPERACION INTEGER, P_TIENDA INTEGER) IS
    SELECT NVL((SELECT 1
                FROM ventas.pvideopr a, ventas.pvrenpag b, ventas.pvartics c 
                WHERE a.cvetda = P_TIENDA AND a.oprcaj = P_OPERACION
                  AND a.status = 0 AND a.tipopr = 1 AND c.clase = 132 AND c.descripcion LIKE '%MOTOCICLETA%'
                  AND b.cvetda = a.cvetda AND b.oprcaj = a.oprcaj AND c.numart = b.numart AND ROWNUM = 1), 0)
    FROM ventas.pvideopr;
    
  VALIDACION INTEGER;
BEGIN
  FECHA_ACTUAL := NULL;
  
  SELECT TRUNC(SYSDATE)
    INTO FECHA_ACTUAL
  FROM DUAL;

  OPEN C_VALIDACION(OPRCAJ_, TIENDA_);
    FETCH C_VALIDACION INTO VALIDACION;
  CLOSE C_VALIDACION;
    
  IF VALIDACION = 1 THEN
    rRET.EXITO := 1;
    rRET.MENSAJE := 'LA OPERACION CONTIENE UN VEHICULO AUTOMOTOR, PROCEDA CON LA OPERACION';
  ELSE 
    rRET.EXITO := -4;
    rRET.MENSAJE := 'LA OPERACION NO CONTIENE UN VEHICULO AUTOMOTOR';
  END IF;

  tRET.EXTEND;
  tRET(tRET.LAST) := rRET;
  
  OPEN OUT_RESULTSET FOR
    SELECT 
      T.EXITO,
      T.MENSAJE
    FROM TABLE (CAST(TRET AS VENTAS.CT_RESULTEXITO)) T;
END;
