create or replace PROCEDURE WEB_USOCFDI(
  OUT_RESULTSET OUT SYS_REFCURSOR
) IS

  tRET VENTAS.CT_USOCFDI := VENTAS.CT_USOCFDI();
  rRET VENTAS.CR_USOCFDI := VENTAS.CR_USOCFDI(NULL, NULL);

  CURSOR C_CONSULTA IS
    SELECT 
      VENTAS.CFDI_USOCFDI.CLAVE, 
      VENTAS.CFDI_USOCFDI.DESCRIPCION 
    FROM VENTAS.CFDI_USOCFDI 
    WHERE IDUSOCFDI IN (1,3,5,6,7,9,22);
      
  R_CONSULTA C_CONSULTA%ROWTYPE;

BEGIN

  OPEN C_CONSULTA;
    
  LOOP
    FETCH C_CONSULTA INTO R_CONSULTA;
    EXIT WHEN C_CONSULTA%NOTFOUND;
        
    rRET.CLAVE := NULL;
    rRET.DESCRIPCION := NULL;
        
    rRET.CLAVE := R_CONSULTA.CLAVE;
    rRET.DESCRIPCION := R_CONSULTA.DESCRIPCION;
        
    tRET.EXTEND;
    tRET(tRET.LAST) := rRET;
  END LOOP;
    
  CLOSE C_CONSULTA;
    
  OPEN OUT_RESULTSET FOR
    SELECT 
      T.CLAVE as CLAVE,
      T.DESCRIPCION as DESCRIPCION
    FROM TABLE (CAST(TRET AS VENTAS.CT_USOCFDI)) T;
    
END;