create or replace PROCEDURE WEB_CATTIENDAS(
  OUT_RESULTSET OUT SYS_REFCURSOR
) IS

  tRET VENTAS.CT_RESULTEXITO := VENTAS.CT_RESULTEXITO();
  rRET VENTAS.CR_RESULTEXITO := VENTAS.CR_RESULTEXITO(0, NULL);

  CURSOR C_CONSULTA IS
    SELECT 
      CVETDA,
      DESCRIPCION
    FROM PVTIENDA
    WHERE IDPLAZA > 0
      AND CVETDA NOT IN (4, 50, 51);
    
  R_CONSULTA C_CONSULTA%ROWTYPE;

BEGIN

  OPEN C_CONSULTA;
  
  LOOP
    FETCH C_CONSULTA INTO R_CONSULTA;
    EXIT WHEN C_CONSULTA%NOTFOUND;
        
    rRET.EXITO := 0;
    rRET.MENSAJE := NULL;
        
    rRET.EXITO := R_CONSULTA.CVETDA;
    rRET.MENSAJE := R_CONSULTA.DESCRIPCION;
        
    tRET.EXTEND;
    tRET(tRET.LAST) := rRET;
  END LOOP;
  
  CLOSE C_CONSULTA;
  
  OPEN OUT_RESULTSET FOR
    SELECT 
      T.EXITO as CVETDA,
      T.MENSAJE as DESCRIPCION
    FROM TABLE (CAST(TRET AS VENTAS.CT_RESULTEXITO)) T;

END;