create or replace PROCEDURE WEB_CATTIENDAS(
  TIPO_CATALOGO  IN INTEGER  DEFAULT 0,
  OUT_RESULTSET OUT SYS_REFCURSOR
) IS

  tRET VENTAS.CT_RESULTEXITO := VENTAS.CT_RESULTEXITO();
  rRET VENTAS.CR_RESULTEXITO := VENTAS.CR_RESULTEXITO(0, NULL);

  CURSOR C_CONSULTA IS
    SELECT 
      CVETDA,
      DESCRIPCION
    FROM PVTIENDA
    WHERE IDPLAZA > 0
      AND CVETDA NOT IN (4, 50, 51);
    
  R_CONSULTA C_CONSULTA%ROWTYPE;

  CURSOR C_CONSULTASDC IS
  SELECT 
    CVETDA,
    DESCRIPCION
  FROM PVTIENDA
  WHERE IDPLAZA > 0
  AND CVETDA NOT IN (4,7, 50, 51);
  
  R_CONSULTASDC C_CONSULTASDC%ROWTYPE;

  CURSOR C_CONSULTABQD IS
  SELECT 
    CVETDA,
    DESCRIPCION
  FROM PVTIENDA
  WHERE IDPLAZA > 0
  AND CVETDA NOT IN (4);
  
  R_CONSULTABQD C_CONSULTABQD%ROWTYPE;

BEGIN

  IF (TIPO_CATALOGO IS NULL OR TIPO_CATALOGO = 0) THEN 

    OPEN C_CONSULTA;
    
    LOOP
      FETCH C_CONSULTA INTO R_CONSULTA;
      EXIT WHEN C_CONSULTA%NOTFOUND;
          
      rRET.EXITO := 0;
      rRET.MENSAJE := NULL;
          
      rRET.EXITO := R_CONSULTA.CVETDA;
      rRET.MENSAJE := R_CONSULTA.DESCRIPCION;
          
      tRET.EXTEND;
      tRET(tRET.LAST) := rRET;
    END LOOP;
    
    CLOSE C_CONSULTA;

  ELSIF TIPO_CATALOGO = 2 THEN 

    OPEN C_CONSULTABQD;  

    LOOP
      FETCH C_CONSULTABQD INTO R_CONSULTABQD;
         
      EXIT WHEN C_CONSULTABQD%NOTFOUND;
          
      rRET.EXITO := 0;
      rRET.MENSAJE := NULL;
          
      rRET.EXITO := R_CONSULTABQD.CVETDA;
      rRET.MENSAJE := R_CONSULTABQD.DESCRIPCION;
          
      tRET.EXTEND;
      tRET(tRET.LAST) := rRET;
    END LOOP;
      
    CLOSE C_CONSULTABQD;

  ELSE

    OPEN C_CONSULTASDC;  
    
      LOOP
        FETCH C_CONSULTASDC INTO R_CONSULTASDC;
         
        EXIT WHEN C_CONSULTASDC%NOTFOUND;
          
        rRET.EXITO := 0;
        rRET.MENSAJE := NULL;
          
        rRET.EXITO := R_CONSULTASDC.CVETDA;
        rRET.MENSAJE := R_CONSULTASDC.DESCRIPCION;
          
        tRET.EXTEND;
        tRET(tRET.LAST) := rRET;
      END LOOP;
      
    CLOSE C_CONSULTASDC;

  END IF;
  
  OPEN OUT_RESULTSET FOR
    SELECT 
      T.EXITO as CVETDA,
      T.MENSAJE as DESCRIPCION
    FROM TABLE (CAST(TRET AS VENTAS.CT_RESULTEXITO)) T;

END;