 create or replace PROCEDURE WEB_VALIDAOPRCAJ_ECOM (
  P_TIENDA INTEGER,
  P_FOLIOECOMM VARCHAR2,
  P_FECHA DATE,
  P_IMPORTE DOUBLE PRECISION,
  OUT_RESULTSET OUT SYS_REFCURSOR
) IS 

  rRET CR_RESULTEXITO := CR_RESULTEXITO(0, NULL);
  tRET CT_RESULTEXITO := CT_RESULTEXITO();
  
  CURSOR C_CONSULTA (P_FOLIOECOMM VARCHAR2, P_TIENDA INTEGER) IS
    SELECT v.IDFAC, v.FECHA, v.STATUS, v.TIPO_FACTURACION, v.TIPOPR, ROUND(v.TOTOPR,2) AS TOTAL_OPR 
    FROM VENTAS.PVIDEOPR v
    INNER JOIN VENTAS.ECOM_FOLIOVENTA o
      ON v.OPRCAJ = o.OPRCAJ
    WHERE o.IDFOLIOECOMMERCE = P_FOLIOECOMM AND v.CVETDA = P_TIENDA;
        
  R_CONSULTA C_CONSULTA%ROWTYPE;
  FECHA_ACTUAL DATE;
  DIFERENCIA DOUBLE PRECISION;
    
BEGIN
  IF P_TIENDA IS NULL THEN
    rRET.EXITO := 0;
    rRET.MENSAJE := 'LA TIENDA ES REQUERIDA';
    tRET.EXTEND;
    tRET(tRET.LAST) := rRET;
    GOTO SALIDA;
  END IF;
  
  IF P_FOLIOECOMM IS NULL THEN
    rRET.EXITO := 0;
    rRET.MENSAJE := 'EL FOLIO ES REQUERIDO';
    tRET.EXTEND;
    tRET(tRET.LAST) := rRET;
    GOTO SALIDA;
  END IF;
  
  IF P_FECHA IS NULL THEN
    rRET.EXITO := 0;
    rRET.MENSAJE := 'LA FECHA ES REQUERIDA';
    tRET.EXTEND;
    tRET(tRET.LAST) := rRET;
    GOTO SALIDA;
  END IF;
  
   IF P_IMPORTE IS NULL THEN
    rRET.EXITO := 0;
    rRET.MENSAJE := 'EL IMPORTE ES REQUERIDO';
    tRET.EXTEND;
    tRET(tRET.LAST) := rRET;
    GOTO SALIDA;
  END IF;
  
  FECHA_ACTUAL := NULL;
  SELECT TRUNC(SYSDATE) INTO FECHA_ACTUAL FROM DUAL;

  OPEN C_CONSULTA(P_FOLIOECOMM,P_TIENDA);
    FETCH C_CONSULTA INTO R_CONSULTA;
    
    IF C_CONSULTA%NOTFOUND THEN
      rRET.EXITO := -1;
      rRET.MENSAJE := 'LA OPERACION EN LA TIENDA EN LÍNEA NO EXISTE';
    ELSE
      DIFERENCIA := R_CONSULTA.TOTAL_OPR - P_IMPORTE;
      IF R_CONSULTA.IDFAC > 0 AND R_CONSULTA.TIPO_FACTURACION = 1 THEN
        rRET.EXITO := -2;
        rRET.MENSAJE := 'LA OPERACION DE CAJA YA SE ENCUENTRA FACTURADA';
        ELSIF R_CONSULTA.STATUS = 1 THEN 
        rRET.EXITO := -3;
        rRET.MENSAJE := 'LA OPERACION DE CAJA SE ENCUENTRA CANCELADA';
      ELSIF R_CONSULTA.TIPOPR <> 1 THEN
        rRET.EXITO := -4;
        rRET.MENSAJE := 'LA OPERACION DE CAJA NO ES UNA OPERACION DE COMPRA';
      ELSIF R_CONSULTA.TIPO_FACTURACION = 2 THEN
        rRET.EXITO := -5;
        rRET.MENSAJE := 'LA OPERACION SE ENCUENTRA FACTURADA GLOBALMENTE';
      ELSIF TO_CHAR(P_FECHA,'DD-MM-YYYY') <> TO_CHAR(R_CONSULTA.FECHA,'DD-MM-YYYY') THEN
        rRET.EXITO := -6;
        rRET.MENSAJE := 'LA FECHA DE LA OPERACION NO ES CORRECTA';
      ELSIF TO_CHAR(FECHA_ACTUAL,'YYYY') <> TO_CHAR(R_CONSULTA.FECHA,'YYYY') THEN
        rRET.EXITO := -7;
        rRET.MENSAJE := 'LA OPERACION NO ES DEL AÑO ACTUAL';
      ELSIF DIFERENCIA > 1 OR DIFERENCIA < -1 THEN 
        rRET.EXITO := -8;
        rRET.MENSAJE := 'EL IMPORTE NO CORRESPONDE A LA TIENDA - OPERACION';
      ELSE
        rRET.EXITO := 1;
        rRET.MENSAJE := 'LA OPERACION PUEDE SER FACTURADA';
      END IF;
    END IF;
  CLOSE C_CONSULTA;
      
  tRET.EXTEND;
  tRET(tRET.LAST) := rRET;
  <<SALIDA>>
  OPEN OUT_RESULTSET FOR
    SELECT 
      T.EXITO,
      T.MENSAJE
    FROM TABLE (CAST(tRET AS VENTAS.CT_RESULTEXITO)) T;
END WEB_VALIDAOPRCAJ_ECOM;

